const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
const LOAD_BOOKS_ERROR = 'LOAD_BOOKS_ERROR';
const LOAD_BOOKINFO_SUCCESS = 'LOAD_BOOKINFO_SUCCESS';
const LOAD_BOOKINFO_ERROR = 'LOAD_BOOKINFO_ERROR';
const CLEAR_STALE_STATE_DATA = 'CLEAR_STALE_STATE_DATA';

export default {
  LOAD_BOOKS_SUCCESS,
  LOAD_BOOKS_ERROR,
  LOAD_BOOKINFO_SUCCESS,
  LOAD_BOOKINFO_ERROR,
  CLEAR_STALE_STATE_DATA
};
