const LOAD_BOOKS_SUCCESS = 'LOAD_BOOKS_SUCCESS';
const LOAD_BOOKS_ERROR = 'LOAD_BOOKS_ERROR';
const LOAD_BOOKINFO_SUCCESS = 'LOAD_BOOKINFO_SUCCESS';
const LOAD_BOOKINFO_ERROR = 'LOAD_BOOKINFO_ERROR';
const CLEAR_STALE_BOOKINFO_DATA = 'CLEAR_STALE_BOOKINFO_DATA';
const REMOVE_BOOKINFO_SUCCESS = 'REMOVE_BOOKINFO_SUCCESS';
const REMOVE_BOOKINFO_ERROR = 'REMOVE_BOOKINFO_ERROR';

export default {
  LOAD_BOOKS_SUCCESS,
  LOAD_BOOKS_ERROR,
  LOAD_BOOKINFO_SUCCESS,
  LOAD_BOOKINFO_ERROR,
  CLEAR_STALE_BOOKINFO_DATA,
  REMOVE_BOOKINFO_SUCCESS,
  REMOVE_BOOKINFO_ERROR
};
